 apiVersion: v1
kind: Service
metadata:
  labels:
    env: prod
  namespace: myname-space
  name: service-first
spec:
  selectors:
    matchLables:
      labels:
        env: prod
  type: nodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    env: prod
  name: deployment-first
  namespace: myname-space
spec:
  replicas: 2
  selectors:
    matchLabels:
      env: prod
  template:
    metadata:
      labels:
        env: prod
    spec:
      containers:
      - name: count-deploy
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 8080
